CREATE DATABASE SISDEF

USE SISDEF

CREATE TABLE USUARIO(
	ID INT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(150) UNIQUE NOT NULL,			
	SENHA VARCHAR(150) NOT NULL
)

CREATE TABLE TIPO_EQUIPAMENTO(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE EQUIPAMENTO(
	ID INT PRIMARY KEY IDENTITY,
	TIPO_EQUIPAMENTO_ID INT FOREIGN KEY REFERENCES TIPO_EQUIPAMENTO(ID) NOT NULL,
	DATA_CADASTRO DATETIME2
)

CREATE TABLE DEFEITO(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE REGISTRO_DEFEITO(
	ID INT PRIMARY KEY IDENTITY,
	DATA_PROBLEMA DATETIME NOT NULL,
	EQUIPAMENTO_ID INT FOREIGN KEY REFERENCES EQUIPAMENTO(ID) NOT NULL,
	DEFEITO_ID INT FOREIGN KEY REFERENCES DEFEITO(ID) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FINAL TIME NOT NULL,
)